// src/themes/themeDefinitions.js

/**
 * Defines the application's color themes.
 * Each theme provides Tailwind CSS class strings for main UI elements.
 * This makes it easy to switch styles globally.
 */

// Shared baseline tokens used by all themes. Individual themes override as needed.
const baseTokens = {
  pageBg: 'bg-gray-50',
  text: 'text-gray-900',
  title: 'text-gray-900',
  subtitle: 'text-gray-700',
  mutedText: 'text-gray-600',
  cardBg: 'bg-white',
  cardBorder: 'border border-gray-200',
  cardShadow: 'shadow-md',
  panelBg: 'bg-white',
  panelBorder: 'border border-gray-200',
  panelShadow: 'shadow-lg',
  tbodyBg: 'bg-white',
  tableStripedBg: 'bg-gray-50',
  tableHover: 'hover:bg-gray-50',
  iconText: 'text-gray-400',
  btnPrimaryBg: 'bg-emerald-600',
  btnPrimaryText: 'text-white',
  btnPrimaryBorder: 'border border-emerald-700',
  btnPrimaryHover: 'hover:bg-emerald-700',
  btnSecondaryBg: 'bg-white',
  btnSecondaryText: 'text-emerald-700',
  btnSecondaryBorder: 'border border-emerald-200',
  btnSecondaryHover: 'hover:bg-emerald-50',
  btnGhostText: 'text-emerald-700',
  btnGhostHover: 'hover:bg-emerald-50',
  btnDangerBg: 'bg-red-600',
  btnDangerText: 'text-white',
  btnDangerBorder: 'border border-red-700',
  btnDangerHover: 'hover:bg-red-700',
  inputBg: 'bg-white',
  inputText: 'text-gray-900',
  inputBorder: 'border border-gray-300',
  inputPlaceholder: 'placeholder:text-gray-400',
  inputFocus: 'focus:border-emerald-500',
  inputRing: 'focus:ring-2 focus:ring-emerald-500 focus:ring-offset-0',
  inputDisabled: 'bg-gray-100',
  badgeBg: 'bg-emerald-100',
  badgeText: 'text-emerald-800',
  badgeBorder: 'border border-emerald-200',
  badgeInfoBg: 'bg-blue-100',
  badgeInfoText: 'text-blue-700',
  badgeSuccessBg: 'bg-green-100',
  badgeSuccessText: 'text-green-700',
  badgeWarningBg: 'bg-amber-100',
  badgeWarningText: 'text-amber-700',
  badgeDangerBg: 'bg-red-100',
  badgeDangerText: 'text-red-700',
  alertInfoBg: 'bg-blue-50',
  alertInfoText: 'text-blue-800',
  alertInfoBorder: 'border border-blue-200',
  alertSuccessBg: 'bg-green-50',
  alertSuccessText: 'text-green-800',
  alertSuccessBorder: 'border border-green-200',
  alertWarningBg: 'bg-amber-50',
  alertWarningText: 'text-amber-800',
  alertWarningBorder: 'border border-amber-200',
  alertErrorBg: 'bg-red-50',
  alertErrorText: 'text-red-800',
  alertErrorBorder: 'border border-red-200',
  modalOverlay: 'bg-black/50',
  modalBg: 'bg-white',
  modalBorder: 'border border-gray-200',
  modalShadow: 'shadow-2xl',
  modalClose: 'text-gray-500 hover:text-gray-700',
  heroBg: 'border border-emerald-100/50 shadow-xl animate-rise bg-gradient-to-br from-emerald-200 via-emerald-50 to-emerald-500',
  heroTitle: 'text-green-800',
  heroSubtitle: 'text-gray-700',
  heroIcon: 'text-emerald-700',
  heroPillBg: 'bg-emerald-50',
  heroPillText: 'text-emerald-800',
  heroPillBorder: 'border border-emerald-100',
  theadBg: 'bg-emerald-600',
  theadText: 'text-green-50',
  tableStripe: 'odd:bg-gray-50',
  pillBg: 'bg-gray-100',
  pillText: 'text-gray-800',
  pillBorder: 'border border-gray-200',
  dashHeroBg: 'bg-gradient-to-br from-emerald-200 via-white to-emerald-500',
  dashHeroBorder: 'border border-emerald-100/70',
  dashHeroShadow: 'shadow-xl',
  dashHeroPillBg: 'bg-emerald-50',
  dashHeroPillText: 'text-emerald-800',
  dashHeroPillBorder: 'border border-emerald-100',
  dashHeroTitle: 'text-emerald-900',
  dashHeroSubtitle: 'text-emerald-700',
  dashHeroGlow: 'from-emerald-200 to-teal-200',
  kpiCardBg: 'bg-white',
  kpiCardBorder: 'border border-gray-200',
  kpiCardShadow: 'shadow-lg',
  kpiGood: 'text-emerald-600',
  kpiWarn: 'text-amber-600',
  kpiBad: 'text-red-600',
  statCard: 'bg-white',
  statCardLabel: 'text-gray-600',
  statCardValue: 'text-gray-900',
};

export const themes = {
  // Theme 1: Original Green (Light) - Default
  Green: {
    ...baseTokens,
    tableStripedBg: 'bg-gray-50',
    tableHover: 'hover:bg-emerald-50',
    sidebarClasses: 'bg-gradient-to-r from-green-100 to-white text-gray-800 border-r-2 border-green-200',
    headerText: 'text-green-800',
    linkHover: 'hover:bg-gradient-to-r hover:from-gray-300 hover:to-green-500 hover:text-black',
    linkText: 'text-gray-800',
    mainBg: 'bg-gray-50',
    logoSvg: 'text-green-600',
    cardBg: 'bg-white',
    border: 'border-gray-300',
    shadow: 'shadow-md',
  },

  // Theme 2: General Dark (Charcoal-Gray Dark) - FULLY UPDATED
  'General Dark': {
    ...baseTokens,
    pageBg: 'bg-gray-900',
    text: 'text-gray-100',
    mutedText: 'text-gray-400',
    title: 'text-gray-100',
    subtitle: 'text-gray-300',
    cardBg: 'bg-gray-800',
    cardBorder: 'border border-gray-700',
    cardShadow: 'shadow-md shadow-gray-900/50',
    panelBg: 'bg-gray-800',
    panelBorder: 'border border-gray-700',
    panelShadow: 'shadow-lg shadow-gray-900/50',
    tbodyBg: 'bg-gray-800',
    tableStripedBg: 'bg-gray-700',
    tableHover: 'hover:bg-gray-700',
    sidebarClasses: 'bg-gray-800 text-gray-200 border-r-2 border-gray-700',
    headerText: 'text-gray-100',
    linkHover: 'hover:bg-gray-700 hover:text-white',
    linkText: 'text-gray-300',
    mainBg: 'bg-gray-900',
    logoSvg: 'text-gray-200',
    iconText: 'text-gray-400',
    btnPrimaryBg: 'bg-gray-600',
    btnPrimaryText: 'text-white',
    btnPrimaryBorder: 'border border-gray-700',
    btnPrimaryHover: 'hover:bg-gray-700',
    btnSecondaryBg: 'bg-gray-800',
    btnSecondaryText: 'text-gray-300',
    btnSecondaryBorder: 'border border-gray-700',
    btnSecondaryHover: 'hover:bg-gray-700',
    btnGhostText: 'text-gray-300',
    btnGhostHover: 'hover:bg-gray-800',
    inputBg: 'bg-gray-800',
    inputText: 'text-gray-100',
    inputBorder: 'border border-gray-600',
    inputFocus: 'focus:border-gray-500',
    inputRing: 'focus:ring-2 focus:ring-gray-500 focus:ring-offset-0',
    inputDisabled: 'bg-gray-900',
    heroBg: 'border border-gray-700 shadow-xl bg-gradient-to-br from-gray-800 via-gray-900 to-gray-700',
    heroTitle: 'text-gray-100',
    heroSubtitle: 'text-gray-300',
    heroIcon: 'text-gray-400',
    theadBg: 'bg-gray-700',
    theadText: 'text-gray-100',
    dashHeroBg: 'bg-gradient-to-br from-gray-800 via-gray-900 to-gray-800',
    dashHeroBorder: 'border border-gray-700',
    dashHeroTitle: 'text-gray-100',
    dashHeroSubtitle: 'text-gray-300',
    dashHeroPillBg: 'bg-gray-800',
    dashHeroPillText: 'text-gray-200',
    dashHeroPillBorder: 'border border-gray-700',
    // Dark-friendly badges
    badgeSuccessBg: 'bg-green-900/30',
    badgeSuccessText: 'text-green-300',
    badgeWarningBg: 'bg-amber-900/30',
    badgeWarningText: 'text-amber-300',
    badgeDangerBg: 'bg-red-900/30',
    badgeDangerText: 'text-red-300',
    badgeBorder: 'border border-gray-700',
    statCardValue: 'text-gray-100',
  },

  // Theme 3: Deep Blue (Dark Navy-Blue with Oceanic Tones) - FULLY UPDATED
  'Deep Blue': {
    ...baseTokens,
    pageBg: 'bg-slate-900',
    text: 'text-blue-100',
    mutedText: 'text-blue-300',
    title: 'text-blue-100',
    subtitle: 'text-blue-300',
    cardBg: 'bg-slate-800',
    cardBorder: 'border border-blue-900',
    cardShadow: 'shadow-md shadow-blue-900/50',
    panelBg: 'bg-slate-800',
    panelBorder: 'border border-blue-800',
    panelShadow: 'shadow-lg shadow-blue-900/50',
    tbodyBg: 'bg-slate-800',
    tableStripedBg: 'bg-gray-800',
    tableHover: 'hover:bg-blue-900',
    sidebarClasses: 'bg-blue-900 text-blue-200 border-r-2 border-blue-700',
    headerText: 'text-blue-300',
    linkHover: 'hover:bg-blue-800 hover:text-white',
    linkText: 'text-blue-200',
    mainBg: 'bg-slate-900',
    logoSvg: 'text-blue-400',
    iconText: 'text-blue-400',
    btnPrimaryBg: 'bg-blue-700',
    btnPrimaryText: 'text-white',
    btnPrimaryBorder: 'border border-blue-800',
    btnPrimaryHover: 'hover:bg-blue-800',
    btnSecondaryBg: 'bg-slate-800',
    btnSecondaryText: 'text-blue-300',
    btnSecondaryBorder: 'border border-blue-800',
    btnSecondaryHover: 'hover:bg-slate-700',
    btnGhostText: 'text-blue-300',
    btnGhostHover: 'hover:bg-slate-800',
    inputBg: 'bg-gray-800',
    inputText: 'text-blue-100',
    inputBorder: 'border border-gray-600',
    inputFocus: 'focus:border-blue-500',
    inputRing: 'focus:ring-2 focus:ring-blue-500 focus:ring-offset-0',
    inputDisabled: 'bg-gray-900',
    heroBg: 'border border-blue-800 shadow-xl bg-gradient-to-br from-blue-900 via-slate-900 to-blue-800',
    heroTitle: 'text-blue-100',
    heroSubtitle: 'text-blue-300',
    heroIcon: 'text-blue-400',
    theadBg: 'bg-blue-800',
    theadText: 'text-blue-50',
    dashHeroBg: 'bg-gradient-to-br from-slate-800 via-blue-950 to-slate-900',
    dashHeroBorder: 'border border-blue-800',
    dashHeroTitle: 'text-blue-100',
    dashHeroSubtitle: 'text-blue-300',
    dashHeroPillBg: 'bg-blue-900',
    dashHeroPillText: 'text-blue-200',
    dashHeroPillBorder: 'border border-blue-800',
    // Dark-friendly badges
    badgeSuccessBg: 'bg-emerald-900/30',
    badgeSuccessText: 'text-emerald-300',
    badgeWarningBg: 'bg-amber-900/30',
    badgeWarningText: 'text-amber-300',
    badgeDangerBg: 'bg-rose-900/30',
    badgeDangerText: 'text-rose-300',
    badgeBorder: 'border border-blue-900/40',
    statCardValue: 'text-blue-100',
  },

  // Theme 4: Royal Purple (Vibrant Light)
  'Royal Purple': {
    ...baseTokens,
    text: 'text-purple-900',
    mutedText: 'text-purple-700',
    title: 'text-purple-900',
    subtitle: 'text-purple-700',
    pageBg: 'bg-white',
    cardBg: 'bg-white',
    cardBorder: 'border border-purple-200',
    cardShadow: 'shadow-md shadow-purple-100',
    panelBg: 'bg-white',
    panelBorder: 'border border-purple-200',
    panelShadow: 'shadow-lg shadow-purple-100',
    tbodyBg: 'bg-white',
    tableStripedBg: 'bg-purple-50',
    tableHover: 'hover:bg-purple-50',
    sidebarClasses: 'bg-purple-50 text-purple-900 border-r-2 border-purple-300',
    headerText: 'text-purple-800',
    linkHover: 'hover:bg-purple-200 hover:text-purple-900',
    linkText: 'text-purple-800',
    mainBg: 'bg-white',
    logoSvg: 'text-purple-600',
    btnPrimaryBg: 'bg-purple-600',
    btnPrimaryText: 'text-white',
    btnPrimaryBorder: 'border border-purple-700',
    btnPrimaryHover: 'hover:bg-purple-700',
    btnSecondaryBg: 'bg-white',
    btnSecondaryText: 'text-purple-700',
    btnSecondaryBorder: 'border border-purple-200',
    btnSecondaryHover: 'hover:bg-purple-50',
    btnGhostText: 'text-purple-700',
    btnGhostHover: 'hover:bg-purple-50',
    inputBg: 'bg-white',
    inputText: 'text-gray-900',
    inputBorder: 'border border-gray-300',
    inputFocus: 'focus:border-purple-500',
    inputRing: 'focus:ring-2 focus:ring-purple-500 focus:ring-offset-0',
    inputDisabled: 'bg-gray-100',
    heroBg: 'border border-purple-100 shadow-xl bg-gradient-to-br from-purple-100 via-white to-purple-200',
    heroTitle: 'text-purple-900',
    heroSubtitle: 'text-purple-700',
    heroIcon: 'text-purple-700',
    theadBg: 'bg-purple-600',
    theadText: 'text-purple-50',
    dashHeroBg: 'bg-gradient-to-br from-purple-50 via-white to-purple-100',
    dashHeroBorder: 'border border-purple-100',
    dashHeroTitle: 'text-purple-900',
    dashHeroSubtitle: 'text-purple-700',
    dashHeroPillBg: 'bg-purple-50',
    dashHeroPillText: 'text-purple-800',
    dashHeroPillBorder: 'border border-purple-100',
    iconText: 'text-purple-600',
  },

  // Theme 5: Sunset Orange (Warm Light)
  'Sunset Orange': {
    ...baseTokens,
    text: 'text-orange-900',
    mutedText: 'text-orange-700',
    title: 'text-orange-900',
    subtitle: 'text-orange-700',
    pageBg: 'bg-white',
    cardBg: 'bg-white',
    cardBorder: 'border border-orange-200',
    cardShadow: 'shadow-md shadow-orange-100',
    panelBg: 'bg-white',
    panelBorder: 'border border-orange-200',
    panelShadow: 'shadow-lg shadow-orange-100',
    tbodyBg: 'bg-white',
    tableStripedBg: 'bg-orange-50',
    tableHover: 'hover:bg-orange-50',
    sidebarClasses: 'bg-orange-50 text-orange-900 border-r-2 border-orange-200',
    headerText: 'text-orange-800',
    linkHover: 'hover:bg-orange-200 hover:text-orange-900',
    linkText: 'text-orange-800',
    mainBg: 'bg-white',
    logoSvg: 'text-orange-500',
    btnPrimaryBg: 'bg-orange-500',
    btnPrimaryText: 'text-white',
    btnPrimaryBorder: 'border border-orange-600',
    btnPrimaryHover: 'hover:bg-orange-600',
    btnSecondaryBg: 'bg-white',
    btnSecondaryText: 'text-orange-700',
    btnSecondaryBorder: 'border border-orange-200',
    btnSecondaryHover: 'hover:bg-orange-50',
    btnGhostText: 'text-orange-700',
    btnGhostHover: 'hover:bg-orange-50',
    inputBg: 'bg-white',
    inputText: 'text-gray-900',
    inputBorder: 'border border-gray-300',
    inputFocus: 'focus:border-orange-500',
    inputRing: 'focus:ring-2 focus:ring-orange-500 focus:ring-offset-0',
    inputDisabled: 'bg-gray-100',
    heroBg: 'border border-orange-100 shadow-xl bg-gradient-to-br from-orange-100 via-white to-orange-200',
    heroTitle: 'text-orange-900',
    heroSubtitle: 'text-orange-700',
    heroIcon: 'text-orange-700',
    theadBg: 'bg-orange-500',
    theadText: 'text-orange-50',
    dashHeroBg: 'bg-gradient-to-br from-orange-50 via-white to-orange-100',
    dashHeroBorder: 'border border-orange-100',
    dashHeroTitle: 'text-orange-900',
    dashHeroSubtitle: 'text-orange-700',
    dashHeroPillBg: 'bg-orange-50',
    dashHeroPillText: 'text-orange-800',
    dashHeroPillBorder: 'border border-orange-100',
    iconText: 'text-orange-600',
  },

  // Theme 6: Black & Teal (Contrast Dark Mode)
  'Black & Teal': {
    ...baseTokens,
    pageBg: 'bg-gray-900',
    text: 'text-teal-50',
    mutedText: 'text-teal-200',
    title: 'text-teal-100',
    subtitle: 'text-teal-200',
    cardBg: 'bg-gray-800',
    cardBorder: 'border border-teal-700',
    cardShadow: 'shadow-lg shadow-teal-900/50',
    panelBg: 'bg-gray-800',
    panelBorder: 'border border-teal-700',
    panelShadow: 'shadow-lg shadow-teal-900/50',
    tbodyBg: 'bg-gray-800',
    tableStripedBg: 'bg-gray-700',
    tableHover: 'hover:bg-teal-900',
    sidebarClasses: 'bg-gray-800 text-teal-300 border-r-2 border-teal-500',
    headerText: 'text-teal-400',
    linkHover: 'hover:bg-teal-700 hover:text-white',
    linkText: 'text-teal-300',
    mainBg: 'bg-gray-900',
    logoSvg: 'text-teal-500',
    btnPrimaryBg: 'bg-teal-600',
    btnPrimaryText: 'text-white',
    btnPrimaryBorder: 'border border-teal-700',
    btnPrimaryHover: 'hover:bg-teal-700',
    btnSecondaryBg: 'bg-gray-800',
    btnSecondaryText: 'text-teal-300',
    btnSecondaryBorder: 'border border-teal-700',
    btnSecondaryHover: 'hover:bg-gray-700',
    btnGhostText: 'text-teal-300',
    btnGhostHover: 'hover:bg-gray-800',
    inputBg: 'bg-gray-800',
    inputText: 'text-teal-100',
    inputBorder: 'border border-gray-600',
    inputFocus: 'focus:border-teal-500',
    inputRing: 'focus:ring-2 focus:ring-teal-500 focus:ring-offset-0',
    inputDisabled: 'bg-gray-900',
    heroBg: 'border border-teal-700 shadow-xl bg-gradient-to-br from-gray-900 via-gray-800 to-teal-900',
    heroTitle: 'text-teal-100',
    heroSubtitle: 'text-teal-200',
    heroIcon: 'text-teal-200',
    theadBg: 'bg-teal-700',
    theadText: 'text-white',
    dashHeroBg: 'bg-gradient-to-br from-gray-900 via-gray-800 to-teal-900',
    dashHeroBorder: 'border border-teal-700',
    dashHeroTitle: 'text-teal-100',
    dashHeroSubtitle: 'text-teal-200',
    dashHeroPillBg: 'bg-gray-800',
    dashHeroPillText: 'text-teal-100',
    dashHeroPillBorder: 'border border-teal-700',
    iconText: 'text-teal-400',
    // Dark-friendly badges
    badgeSuccessBg: 'bg-teal-900/30',
    badgeSuccessText: 'text-teal-300',
    badgeWarningBg: 'bg-amber-900/30',
    badgeWarningText: 'text-amber-300',
    badgeDangerBg: 'bg-red-900/30',
    badgeDangerText: 'text-red-300',
    badgeBorder: 'border border-teal-700/40',
    statCardValue: 'text-teal-100',
  },

  // Theme 7: Vibrant Magenta (New Theme)
  'Vibrant Magenta': {
    ...baseTokens,
    text: 'text-pink-900',
    mutedText: 'text-pink-700',
    title: 'text-pink-900',
    subtitle: 'text-pink-700',
    pageBg: 'bg-white',
    cardBg: 'bg-white',
    cardBorder: 'border border-pink-200',
    cardShadow: 'shadow-md shadow-pink-100',
    panelBg: 'bg-white',
    panelBorder: 'border border-pink-200',
    panelShadow: 'shadow-lg shadow-pink-100',
    tbodyBg: 'bg-white',
    tableStripedBg: 'bg-pink-50',
    tableHover: 'hover:bg-pink-50',
    sidebarClasses: 'bg-pink-100 text-pink-900 border-r-2 border-pink-400',
    headerText: 'text-pink-700',
    linkHover: 'hover:bg-pink-300 hover:text-pink-900',
    linkText: 'text-pink-800',
    mainBg: 'bg-white',
    logoSvg: 'text-pink-600',
    btnPrimaryBg: 'bg-pink-600',
    btnPrimaryText: 'text-white',
    btnPrimaryBorder: 'border border-pink-700',
    btnPrimaryHover: 'hover:bg-pink-700',
    btnSecondaryBg: 'bg-white',
    btnSecondaryText: 'text-pink-700',
    btnSecondaryBorder: 'border border-pink-200',
    btnSecondaryHover: 'hover:bg-pink-50',
    btnGhostText: 'text-pink-700',
    btnGhostHover: 'hover:bg-pink-50',
    inputBg: 'bg-white',
    inputText: 'text-gray-900',
    inputBorder: 'border border-gray-300',
    inputFocus: 'focus:border-pink-500',
    inputRing: 'focus:ring-2 focus:ring-pink-500 focus:ring-offset-0',
    inputDisabled: 'bg-gray-100',
    heroBg: 'border border-pink-200 shadow-xl bg-gradient-to-br from-pink-100 via-white to-pink-200',
    heroTitle: 'text-pink-900',
    heroSubtitle: 'text-pink-700',
    heroIcon: 'text-pink-700',
    theadBg: 'bg-pink-600',
    theadText: 'text-pink-50',
    dashHeroBg: 'bg-gradient-to-br from-pink-50 via-white to-pink-100',
    dashHeroBorder: 'border border-pink-200',
    dashHeroTitle: 'text-pink-900',
    dashHeroSubtitle: 'text-pink-700',
    dashHeroPillBg: 'bg-pink-50',
    dashHeroPillText: 'text-pink-800',
    dashHeroPillBorder: 'border border-pink-200',
    iconText: 'text-pink-600',
  },
};

// The default theme to be used on initial load
export const defaultThemeName = 'Green';
